import { Link } from 'react-router-dom'

/**
 * Terms of Service — a public page (no auth) linked from the login screen
 * and Settings. Written in plain language and kept honest about the beta:
 * community/AI-drafted content, AI tutor limits, and what we store.
 */

const LAST_UPDATED = 'July 16, 2026'

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-2">
      <h2 className="text-base font-semibold text-gray-900">{title}</h2>
      <div className="text-sm text-gray-600 space-y-2">{children}</div>
    </section>
  )
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-2xl mx-auto px-4 py-10 space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Terms of Service</h1>
          <p className="text-sm text-gray-500 mt-1">
            PolyglotSRS · Last updated {LAST_UPDATED}
          </p>
        </div>

        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 space-y-6">
          <Section title="1. What PolyglotSRS is">
            <p>
              PolyglotSRS is a spaced-repetition language-learning service:
              grammar and vocabulary decks, typed reviews, and an optional AI
              tutor. By creating an account or using the service you agree to
              these terms.
            </p>
            <p>
              The service is currently in <strong>beta</strong>. Features may
              change, break, or be removed, and we may need to reset or migrate
              data as the product evolves. We will avoid that wherever possible
              and tell you when it happens.
            </p>
          </Section>

          <Section title="2. Your account">
            <p>
              You need an account to study. Keep your credentials to yourself;
              you are responsible for activity under your account. You must be
              at least 13 years old (or the minimum age of digital consent in
              your country) to use the service.
            </p>
          </Section>

          <Section title="3. Acceptable use">
            <p>
              Don't abuse the service: no attempts to break authentication or
              access other people's data, no scraping or bulk-extracting
              content, no using the AI tutor or audio generation for anything
              other than your own language study, and no reselling access.
              Rate limits and usage allowances (for example, tutor message
              allowances) are part of the service; circumventing them is a
              breach of these terms.
            </p>
          </Section>

          <Section title="4. Learning content and accuracy">
            <p>
              Lessons, drills, and explanations are drafted with the help of AI
              and reviewed on an ongoing basis; native-speaker review is still
              in progress for parts of the catalogue, and some items are marked
              as drafts. Content may contain errors. If something looks wrong,
              use the in-app report option — corrections are part of how the
              beta improves.
            </p>
          </Section>

          <Section title="5. The AI tutor">
            <p>
              Tutor conversations are generated by an AI model. The tutor can
              be wrong, and nothing it says is professional advice. Tutor
              messages are subject to the allowance on your plan. To keep
              coaching consistent between sessions, the tutor stores session
              summaries and the study notes it takes about your progress;
              these are visible to you in the app and are deleted with your
              account. Please don't share sensitive personal information in
              tutor chats.
            </p>
          </Section>

          <Section title="6. Plans and billing">
            <p>
              Paid plans are billed through Stripe. Subscriptions renew
              automatically until cancelled; you can cancel any time from the
              billing portal in Settings, and access continues to the end of
              the paid period. Prices may change — existing subscribers get
              notice before a change affects them. Usage allowances reset on
              their stated cycle (daily or monthly) and unused allowance does
              not roll over.
            </p>
          </Section>

          <Section title="7. Your content">
            <p>
              Text you bring to the service (notes, personal sentences, custom
              cards) stays yours. You give us permission to store and process
              it to run the service — for example, generating cloze cards or
              audio from it. We don't use your content to train models, and we
              don't sell it.
            </p>
          </Section>

          <Section title="8. What we store">
            <p>
              To run the service we store your email address, your study
              settings, your review history (which drives the spaced-repetition
              scheduling), your tutor conversations and the tutor's notes, and
              billing status (payment details themselves are held by Stripe,
              not us). Deleting your account removes your personal data from
              the service.
            </p>
          </Section>

          <Section title="9. Audio">
            <p>
              Pronunciation audio is synthesized with neural text-to-speech
              voices. It is generally accurate but is machine-generated and may
              occasionally mispronounce a word — where human recordings exist,
              they take precedence.
            </p>
          </Section>

          <Section title="10. Termination">
            <p>
              You can stop using the service or delete your account at any
              time. We may suspend or terminate accounts that breach these
              terms, with notice where practical. If we ever discontinue the
              service, we will give reasonable notice.
            </p>
          </Section>

          <Section title="11. Disclaimers and liability">
            <p>
              The service is provided "as is", without warranties of any kind,
              during the beta especially. To the maximum extent permitted by
              law, our liability for any claim related to the service is
              limited to the amount you paid us in the twelve months before
              the claim.
            </p>
          </Section>

          <Section title="12. Changes to these terms">
            <p>
              We may update these terms as the service evolves. Material
              changes will be announced in the app before they take effect;
              continuing to use the service after that means you accept the
              updated terms.
            </p>
          </Section>

          <Section title="13. Contact">
            <p>
              Questions about these terms or your data: contact the operator
              through the in-app report option or the address on the project's
              GitHub page.
            </p>
          </Section>
        </div>

        <div className="text-center">
          <Link to="/" className="text-sm text-lang hover:underline">
            ← Back to PolyglotSRS
          </Link>
        </div>
      </div>
    </div>
  )
}
