/**
 * Gym picker labels, keyed for translation.
 *
 * The picker is a fixed menu of the app's practice categories — chrome, not
 * per-learner content — so its labels live in the i18n catalog like the
 * column headers beside them. The map is keyed by the ENGLISH label the
 * manifest ships, which makes the fallback self-correcting: once a language
 * has DB label overlays (gym_label_translations), the API sends an already-
 * translated label, that string matches no English key, and it passes
 * through untouched. Anything unknown renders verbatim.
 */
export const GYM_LABEL_KEYS: Record<string, string> = {
  '-an locative focus': 'gymForms.anLocativeFocus',
  '-i': 'gymForms.i',
  '-in object focus': 'gymForms.inObjectFocus',
  '-kan': 'gymForms.kan',
  '-um- actor focus': 'gymForms.umActorFocus',
  '1st declension': 'gymForms.1stDeclension',
  '2nd declension': 'gymForms.2ndDeclension',
  '3rd decl. neuters': 'gymForms.3rdDeclNeuters',
  '3rd declension': 'gymForms.3rdDeclension',
  '4th/5th declension': 'gymForms.4th5thDeclension',
  'Ability': 'gymForms.ability',
  'Ablative': 'gymForms.ablative',
  'Ablative absolute': 'gymForms.ablativeAbsolute',
  'Acc. + infinitive': 'gymForms.accInfinitive',
  'Accusative': 'gymForms.accusative',
  'Accusative (what)': 'gymForms.accusativeWhat',
  'Accusative (whom)': 'gymForms.accusativeWhom',
  'Adjective -e': 'gymForms.adjectiveE',
  'Adjective endings': 'gymForms.adjectiveEndings',
  'Adjective gender': 'gymForms.adjectiveGender',
  'Adjectives': 'gymForms.adjectives',
  'Adverbs': 'gymForms.adverbs',
  'Agreement': 'gymForms.agreement',
  'Aorist': 'gymForms.aorist',
  'Arriving & leaving': 'gymForms.arrivingLeaving',
  'Articles': 'gymForms.articles',
  'Articles a/an': 'gymForms.articlesAAn',
  'Articulated prepositions': 'gymForms.articulatedPrepositions',
  'Aspect choice': 'gymForms.aspectChoice',
  'Binyan idioms': 'gymForms.binyanIdioms',
  'Broken plurals': 'gymForms.brokenPlurals',
  'But / and': 'gymForms.butAnd',
  'Can (tavanestan)': 'gymForms.canTavanestan',
  'Can / can\'t': 'gymForms.canCanT',
  'Causative': 'gymForms.causative',
  'Causatives': 'gymForms.causatives',
  'Classifiers': 'gymForms.classifiers',
  'Commands': 'gymForms.commands',
  'Comparative': 'gymForms.comparative',
  'Comparatives': 'gymForms.comparatives',
  'Comparison': 'gymForms.comparison',
  'Comparison 보다': 'gymForms.comparison2',
  'Conditional': 'gymForms.conditional',
  'Conditionals': 'gymForms.conditionals',
  'Conditionals (אם)': 'gymForms.conditionals2',
  'Contractions': 'gymForms.contractions',
  'Counterfactuals': 'gymForms.counterfactuals',
  'Counting forms': 'gymForms.countingForms',
  'Dative': 'gymForms.dative',
  'Dative (to whom)': 'gymForms.dativeToWhom',
  'De / het': 'gymForms.deHet',
  'Definite article': 'gymForms.definiteArticle',
  'Definite suffix': 'gymForms.definiteSuffix',
  'Deictics': 'gymForms.deictics',
  'Demonstratives': 'gymForms.demonstratives',
  'Deponents': 'gymForms.deponents',
  'Diminutives': 'gymForms.diminutives',
  'Dual': 'gymForms.dual',
  'Ergative ने': 'gymForms.ergative',
  'Evidential (-miş)': 'gymForms.evidentialMi',
  'Ezafe': 'gymForms.ezafe',
  'Ezafe chains': 'gymForms.ezafeChains',
  'Formal register': 'gymForms.formalRegister',
  'Formal ㅂ니다': 'gymForms.formal',
  'Forms II–IV': 'gymForms.formsIiIv',
  'Forms V–X': 'gymForms.formsVX',
  'Future': 'gymForms.future',
  'Future (completed)': 'gymForms.futureCompleted',
  'Future (ir)': 'gymForms.futureIr',
  'Future (ongoing)': 'gymForms.futureOngoing',
  'Future (pa\'al)': 'gymForms.futurePaAl',
  'Future subjunctive': 'gymForms.futureSubjunctive',
  'Gender': 'gymForms.gender',
  'Gender (incl. neuter)': 'gymForms.genderInclNeuter',
  'Genitive': 'gymForms.genitive',
  'Genitive & dative': 'gymForms.genitiveDative',
  'Genitive (there\'s no…)': 'gymForms.genitiveThereSNo',
  'Genitive (whose)': 'gymForms.genitiveWhose',
  'Genitive + possessed': 'gymForms.genitivePossessed',
  'Genitive-dative': 'gymForms.genitiveDative2',
  'Going by vehicle': 'gymForms.goingByVehicle',
  'Going on foot': 'gymForms.goingOnFoot',
  'Habitual past': 'gymForms.habitualPast',
  'Hif\'il past/future': 'gymForms.hifIlPastFuture',
  'Hitpa\'el': 'gymForms.hitpaEl',
  'Honorific forms': 'gymForms.honorificForms',
  'If (으)면': 'gymForms.if',
  'Imperative': 'gymForms.imperative',
  'Imperfect': 'gymForms.imperfect',
  'Indefinite article': 'gymForms.indefiniteArticle',
  'Infinitive': 'gymForms.infinitive',
  'Infinitive as noun': 'gymForms.infinitiveAsNoun',
  'Instrumental (with what)': 'gymForms.instrumentalWithWhat',
  'Irregular past': 'gymForms.irregularPast',
  'Irregular presents': 'gymForms.irregularPresents',
  'Irregular preterites': 'gymForms.irregularPreterites',
  'Irregular stems': 'gymForms.irregularStems',
  'Iḍāfa': 'gymForms.iFa',
  'Jussive (لم)': 'gymForms.jussive',
  'Konjunktiv II': 'gymForms.konjunktivIi',
  'Light verbs': 'gymForms.lightVerbs',
  'Literary past': 'gymForms.literaryPast',
  'Locative': 'gymForms.locative',
  'Long chains': 'gymForms.longChains',
  'Modal verbs': 'gymForms.modalVerbs',
  'Must / may': 'gymForms.mustMay',
  'My / your / our': 'gymForms.myYourOur',
  'Necessity': 'gymForms.necessity',
  'Negation': 'gymForms.negation',
  'Negative past': 'gymForms.negativePast',
  'Negative present': 'gymForms.negativePresent',
  'Nif\'al': 'gymForms.nifAl',
  'Noun modifiers': 'gymForms.nounModifiers',
  'Numbers': 'gymForms.numbers',
  'Numbers & ta': 'gymForms.numbersTa',
  'Object clitics': 'gymForms.objectClitics',
  'Object marker ra': 'gymForms.objectMarkerRa',
  'Object marker את': 'gymForms.objectMarker',
  'Object pronouns': 'gymForms.objectPronouns',
  'Object 을/를': 'gymForms.object',
  'Oblique case': 'gymForms.obliqueCase',
  'Partitive': 'gymForms.partitive',
  'Passato prossimo (avere)': 'gymForms.passatoProssimoAvere',
  'Passato prossimo (essere)': 'gymForms.passatoProssimoEssere',
  'Passive': 'gymForms.passive',
  'Passive 1 vs 2': 'gymForms.passive1Vs2',
  'Passive aorist': 'gymForms.passiveAorist',
  'Passé composé (avoir)': 'gymForms.passComposAvoir',
  'Passé composé (être)': 'gymForms.passComposTre',
  'Past': 'gymForms.past',
  'Past (-di)': 'gymForms.pastDi',
  'Past (pa\'al pl.)': 'gymForms.pastPaAlPl',
  'Past (pa\'al sg.)': 'gymForms.pastPaAlSg',
  'Past (perifràstic)': 'gymForms.pastPerifrStic',
  'Past perfect': 'gymForms.pastPerfect',
  'Past simple': 'gymForms.pastSimple',
  'Past subjunctive': 'gymForms.pastSubjunctive',
  'Perfect': 'gymForms.perfect',
  'Perfect (haben)': 'gymForms.perfectHaben',
  'Perfect (sein)': 'gymForms.perfectSein',
  'Perfect compus': 'gymForms.perfectCompus',
  'Perfect passive': 'gymForms.perfectPassive',
  'Perfect tenses': 'gymForms.perfectTenses',
  'Personal infinitive': 'gymForms.personalInfinitive',
  'Pi\'el past/future': 'gymForms.piElPastFuture',
  'Pluperfect': 'gymForms.pluperfect',
  'Plural': 'gymForms.plural',
  'Plural -ha': 'gymForms.pluralHa',
  'Plural agreement': 'gymForms.pluralAgreement',
  'Plurals': 'gymForms.plurals',
  'Possession של': 'gymForms.possession',
  'Possession का/के/की': 'gymForms.possession2',
  'Possessive articles': 'gymForms.possessiveArticles',
  'Possessive endings': 'gymForms.possessiveEndings',
  'Possessive suffixes': 'gymForms.possessiveSuffixes',
  'Possessive/demonstrative': 'gymForms.possessiveDemonstrative',
  'Possessives': 'gymForms.possessives',
  'Postpositions': 'gymForms.postpositions',
  'Preposition endings': 'gymForms.prepositionEndings',
  'Prepositional (where)': 'gymForms.prepositionalWhere',
  'Present': 'gymForms.present',
  'Present (1st conj.)': 'gymForms.present1stConj',
  'Present (2nd conj.)': 'gymForms.present2ndConj',
  'Present (3rd/4th conj.)': 'gymForms.present3rd4thConj',
  'Present (hif\'il)': 'gymForms.presentHifIl',
  'Present (pa\'al)': 'gymForms.presentPaAl',
  'Present (pi\'el)': 'gymForms.presentPiEl',
  'Present (polite)': 'gymForms.presentPolite',
  'Present -a': 'gymForms.presentA',
  'Present -ar': 'gymForms.presentAr',
  'Present -are': 'gymForms.presentAre',
  'Present -ea/-e/-i': 'gymForms.presentEaEI',
  'Present -er': 'gymForms.presentEr',
  'Present -er/-ir': 'gymForms.presentErIr',
  'Present -ere/-ire': 'gymForms.presentEreIre',
  'Present -ir/-re': 'gymForms.presentIrRe',
  'Present -re/-ir': 'gymForms.presentReIr',
  'Present continuous': 'gymForms.presentContinuous',
  'Present passive': 'gymForms.presentPassive',
  'Present perfect': 'gymForms.presentPerfect',
  'Present simple': 'gymForms.presentSimple',
  'Preterite': 'gymForms.preterite',
  'Preterite irregulars': 'gymForms.preteriteIrregulars',
  'Pretérito perfeito': 'gymForms.pretRitoPerfeito',
  'Progressive': 'gymForms.progressive',
  'Pronouns': 'gymForms.pronouns',
  'Präteritum': 'gymForms.prTeritum',
  'Pu\'al & huf\'al': 'gymForms.puAlHufAl',
  'Purpose ut/ne': 'gymForms.purposeUtNe',
  'Question words': 'gymForms.questionWords',
  'Questions': 'gymForms.questions',
  'Quotes 다고': 'gymForms.quotes',
  'Real conditionals': 'gymForms.realConditionals',
  'Reason (으)니까': 'gymForms.reason',
  'Reason 아/어서': 'gymForms.reason2',
  'Recent perfective': 'gymForms.recentPerfective',
  'Reciprocal': 'gymForms.reciprocal',
  'Reduplication': 'gymForms.reduplication',
  'Reflexives (-ся)': 'gymForms.reflexives',
  'Register': 'gymForms.register',
  'Register switching': 'gymForms.registerSwitching',
  'Relative ke': 'gymForms.relativeKe',
  'Relative qui': 'gymForms.relativeQui',
  'Relative אשר': 'gymForms.relative',
  'Relative ש־': 'gymForms.relative2',
  'Reported speech': 'gymForms.reportedSpeech',
  'Result tam...ut': 'gymForms.resultTamUt',
  'Root & binyan': 'gymForms.rootBinyan',
  'Separable verbs': 'gymForms.separableVerbs',
  'Short forms': 'gymForms.shortForms',
  'Simple past': 'gymForms.simplePast',
  'Simple present': 'gymForms.simplePresent',
  'Smichut': 'gymForms.smichut',
  'Sound plurals': 'gymForms.soundPlurals',
  'Subject vs object': 'gymForms.subjectVsObject',
  'Subject 이/가': 'gymForms.subject',
  'Subjunctive': 'gymForms.subjunctive',
  'Subjunctive (να)': 'gymForms.subjunctive2',
  'Superlatives': 'gymForms.superlatives',
  'The article ال': 'gymForms.theArticle',
  'Third-person -s': 'gymForms.thirdPersonS',
  'Three aspects': 'gymForms.threeAspects',
  'Time clauses': 'gymForms.timeClauses',
  'Topic 은/는': 'gymForms.topic',
  'Two-way prepositions': 'gymForms.twoWayPrepositions',
  'Unreal conditionals': 'gymForms.unrealConditionals',
  'Vav-conversive': 'gymForms.vavConversive',
  'Verbal nouns': 'gymForms.verbalNouns',
  'Word order': 'gymForms.wordOrder',
  'Would (бы)': 'gymForms.would',
  'Written vs. spoken': 'gymForms.writtenVsSpoken',
  'Zero copula': 'gymForms.zeroCopula',
  'ang pronouns': 'gymForms.angPronouns',
  'ber- intransitive': 'gymForms.berIntransitive',
  'cum-clauses': 'gymForms.cumClauses',
  'dashtan (to have)': 'gymForms.dashtanToHave',
  'di- passive': 'gymForms.diPassive',
  'haben (present)': 'gymForms.habenPresent',
  'hebben (present)': 'gymForms.hebbenPresent',
  'hic & ille': 'gymForms.hicIlle',
  'i- focus': 'gymForms.iFocus',
  'in + case': 'gymForms.inCase',
  'ke-an / per-an': 'gymForms.keAnPerAn',
  'ma- / maka-': 'gymForms.maMaka',
  'ma- adjectives': 'gymForms.maAdjectives',
  'mag- actor focus': 'gymForms.magActorFocus',
  'meN- active': 'gymForms.menActive',
  'memper-': 'gymForms.memper',
  'ng pronouns': 'gymForms.ngPronouns',
  'peN- agent': 'gymForms.penAgent',
  'possum (can)': 'gymForms.possumCan',
  'sa pronouns': 'gymForms.saPronouns',
  'se-': 'gymForms.se',
  'sein (present)': 'gymForms.seinPresent',
  'si-clauses': 'gymForms.siClauses',
  'sum (to be)': 'gymForms.sumToBe',
  'ta (so that / until)': 'gymForms.taSoThatUntil',
  'ter-': 'gymForms.ter',
  'zijn (present)': 'gymForms.zijnPresent',
  'Свой (one\'s own)': 'gymForms.oneSOwn',
  'יש לי (have)': 'gymForms.have',
  '에 vs 에서': 'gymForms.vs',
}
