"""Thai → Latin reading (RTGS), from a committed dictionary.

Thai was the last non-Roman script here with no reading — 3,754 words and
4,376 sentences. Its deferral outlasted every other because the difficulty is
real: RTGS is not a character mapping. Thai writes vowels before, above, below
and after their consonant, leaves some implicit, and marks no boundaries
between words.

**The first attempt was built, measured, and rejected.** A romanizer over
pythainlp's two engines went through the same adversarial verification Greek
and Korean passed with one systematic defect each. Thai returned 38 defects in
seven classes, scoring 6/18 on the confirmed set — and the misses were ordinary
words: สุขภาพ (health), อิสระ (freedom), ฝรั่งเศส (France), and ไหม, the
question particle ending a large share of all Thai questions, read as two
syllables *haimai*.

Looking at WHICH words failed is what solved it. They were not rule failures;
they were lexical ones — Pali-derived compounds whose linking syllable no rule
predicts (สุก-ขะ-พาบ), and the silent leading ห that marks tone class rather
than a sound. A dictionary fixes exactly that class, and this repo already had
one on disk: the Thai Wiktionary extract carries a "Royal Institute" (RTGS)
romanisation for 17,289 words, covering 100% of the course vocabulary in every
frequency band and 86% of every distinct token the corpus uses.

So the readings are looked up, not computed. `data/th_readings.tsv` is that
table, 149 KB, generated by `scripts/build_th_readings.py`.

**Segmentation without a dependency.** Thai marks no word boundaries, so a
reading still needs one — but a longest-match walk over the table itself
reproduces the segmentation the table was built from, in thirty lines and with
nothing to install. pythainlp is an optional extra, needed only to regenerate.

**Full coverage or no reading.** If any Thai run in the text has no dictionary
entry, this returns "" rather than a partial line. A reading with a hole in it
is read as a whole by someone who cannot see the hole.

**Tone is still missing, and that is the standard's limit, not a gap in the
data.** RTGS carries no tone: คำ and ค่ำ are both *kham*. Thai is tonal, so
this tells a learner how to approximate a word, never how to say it. The
Wiktionary rows carry a Paiboon tone-marked form too and it is kept in the
third column of the table against a future tone layer — but 34% of Paiboon
entries use IPA letters (`gɔɔ-rá-nii`) that a learner cannot read, so turning
that into a shippable notation is its own piece of work.
"""
from __future__ import annotations

import csv
import logging
from functools import lru_cache
from pathlib import Path

logger = logging.getLogger(__name__)

READINGS_TSV = Path(__file__).resolve().parents[3] / "data" / "th_readings.tsv"
THAI_START, THAI_END = "฀", "๿"


def _is_thai(ch: str) -> bool:
    return THAI_START <= ch <= THAI_END


@lru_cache(maxsize=1)
def _readings() -> tuple[dict[str, str], int]:
    """(word -> RTGS, longest key) — loaded once."""
    table: dict[str, str] = {}
    try:
        with READINGS_TSV.open(encoding="utf-8-sig", newline="") as handle:
            for row in csv.DictReader(handle, delimiter="\t"):
                word = (row.get("word") or "").strip()
                rtgs = (row.get("rtgs") or "").strip()
                if word and rtgs:
                    table[word] = rtgs
    except OSError as exc:  # noqa: BLE001 — a missing table must never 500
        logger.warning("thai readings table unavailable: %s", exc)
        return {}, 0
    return table, max((len(w) for w in table), default=0)


def _segment(run: str) -> list[str] | None:
    """Longest-match over the reading table. None when any part is unknown —
    the caller then emits no reading at all rather than a partial one."""
    table, longest = _readings()
    if not table:
        return None
    out: list[str] = []
    i, n = 0, len(run)
    while i < n:
        for size in range(min(longest, n - i), 0, -1):
            chunk = run[i:i + size]
            if chunk in table:
                out.append(table[chunk])
                i += size
                break
        else:
            return None
    return out


def thai_to_roman(text: str) -> str:
    """An RTGS reading of *text*, word-segmented, or "" when the dictionary
    does not cover it. Non-Thai runs pass through verbatim, which is what
    keeps a cloze blank a blank — romanising the raw sentence instead would
    print the hidden word in Latin letters above its own blank."""
    if not text or not any(_is_thai(c) for c in text):
        return ""

    segments: list[tuple[bool, str]] = []
    for ch in text:
        thai = _is_thai(ch)
        if segments and segments[-1][0] == thai:
            segments[-1] = (thai, segments[-1][1] + ch)
        else:
            segments.append((thai, ch))

    out: list[str] = []
    for thai, chunk in segments:
        if not thai:
            # A non-Thai run lands flush against the romanized words either
            # side, because Thai carries no spaces of its own. Pad the ones
            # that are WORDS — `{{answer}}`, `___`, an embedded Latin name —
            # and leave bare punctuation hugging its neighbour.
            if any(c.isalnum() or c == "_" for c in chunk):
                out.append(" " + chunk.strip() + " ")
            else:
                out.append(chunk)
            continue
        words = _segment(chunk)
        if words is None:
            return ""
        out.append(" ".join(words))

    return " ".join("".join(out).split())
