import type { Glyph } from '../../../api/strokes'
import arabic from './arabic.json'
import cyrillic from './cyrillic.json'

/**
 * The PROVISIONAL stroke library (docs/plans/handwriting.md, §13): the
 * textbook order and direction of each letter's strokes in a schematic
 * shape, generated by scripts/strokes/gen_provisional.py, bundled so
 * the guided modes teach *something true* before a speaker has traced
 * the script — and before migration 20261023 has put the same rows in
 * the database. A form the server knows always wins; a bundled one has
 * an id the server will not accept, so nothing is recorded against it.
 */
interface Bundle { script: string; glyphs: Omit<Glyph, 'id'>[] }
const BUNDLES: Record<string, Bundle> = {
  arabic: arabic as Bundle,
  cyrillic: cyrillic as Bundle,
}

export function isProvisionalId(id: string): boolean {
  return id.startsWith('prov:')
}

/** Server glyphs first; bundled forms fill the gaps for this style. */
export function withProvisional(script: string, style: string, glyphs: Glyph[]): Glyph[] {
  const bundle = BUNDLES[script]
  if (!bundle) return glyphs
  const have = new Set(glyphs.map((g) => `${g.glyph}|${g.form}`))
  const extra = bundle.glyphs
    .filter((g) => g.style === style && !have.has(`${g.glyph}|${g.form}`))
    .map((g) => ({ ...g, id: `prov:${script}|${g.glyph}|${g.form}|${style}` } as Glyph))
  return extra.length ? [...glyphs, ...extra] : glyphs
}
